openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
tags:
  - parameter_set
paths:
  /compute:
    post:
      summary: compute
      operationId: compute
      tags:
        - parameter_set 
      requestBody: 
        description:  "set of parameters" 
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ParameterSet"
      responses:
        '201':
          description: success
        '400':
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    ParameterSet:
      type: object
      required:
        - B_E_a
        - B_I_0
        - B_K_V
        - B_P___M
        - B_R_A
        - C_D
        - C_L
        - C_dcs 
        - C_L_max
        - C 
        - E_B
        - g
        - K_V
        - I_in
        - I_0
        - m_B
        - m_M
        - M_tip
        - m_total
        - m_0
        - P_in
        - P_out
        - p_out___max
        - R_p
        - R_a
        - r
        - S_w
        - T
        - tcs
        - V_F
        - V_in
        - V_l
        - V_st
        - W_a
        - n_D
        - n_P
        - n_P___ideal
        - n_S
        - p_a
        - Q
        - Z
      properties:
        B_E_a:
          type: number
          format: float
          description: "battery_nenrgy_distribution"        
        B_I_0:
          type: number
          format: float
          description: "no-load current parameter"
        B_K_V:
          type: number
          format: float
          description: "motor speed-constant parameter"
        B_P___M:
          type: number
          format: float
          description: "maximum power-to-mass ratio"
        B_R_A:
          type: number
          format: float
          description: "internal-resitance parameter"
        C_D:
          type: number
          format: float
          description: "vehicles drag coefficient"
        C_L:
          type: number
          format: float
          description: "vehicles lift coefficient"
        C_dcs:
          type: number
          format: float
          description: "blade cross- sectional drag cofficient"  
        C_L_max:
          type: number
          format: float
          description: " vehicles max lift coefficient"
        c:
          type: number
          format: float
          description: "chord"
        E_B:
          type: number
          format: float
          description: "battery energy capacity"
        g:
          type: number
          format: float
          description: "gravity acceleration"
        K_V:
          type: number
          format: float
          description: "motor speed constant"
        I_in:
          type: number
          format: float
          description: "driver input current"
        I_0:
          type: number
          format: float
          description: "motor no-load current"
        m_B:
          type: number
          format: float
          description:  "battery-ack mass"
        m_M:
          type: number
          format: float
          description: "eletric motor mass"
        M_tip:
          type: number
          format: float
          description: "blade tip match memeber"
        m_total:
          type: number
          format: float
          description: "total vehicle mass"
        m_0:
          type: number
          format: float
          description: "vehocle mass without the propulsion system"
        P_in:
          type: number
          format: float
          description: "electric system input power"
        P_out:
          type: number 
          format: float
          description: "motor out power"
        p_out___max:
          type: number
          format: float
          description: "maximum motor output power"
        R_p:
          type: number 
          format: float
          description: "propeller radius"
        R_a:
          type: number
          format: float
          description: "motor ressistance"
        r:
          type: number
          format: float
          description: "radial coordinate"
        S_w:
          type: number
          format: float
          description: "wing area"
        T:
          type: number
          format: float
          description: "thrust"
        tcs:
          type: number
          format: float
          description:  "cross sectional thickness"
        V_F:
          type: number
          format: float
          description: "airspeed"
        V_in:
          type: number
          format: float
          description: "driver input voltage"
        V_l:
          type: number
          format: float
          description: "loitering airspeed"
        V_st:
          type: number
          format: float
          description:  "stall airspeed"
        W_a:
          type: number
          format: float
          description: "axial induced velocity"
        n_D:
          type: number 
          format: float
          description: "driver efficiency"
        n_P:
          type: number
          format: float
          description: "propeller efficiency"
        n_P___ideal:
          type: number
          format: float
          description: "ideal propeller efficiency"
        n_S:
          type: number
          format: float
          description: " electric system efficiency"
        p_a:
          type: number
          format: float
          description: "air density"
        Q:
          type: number
          format: float
          description: "maximum von Mises Stress"
        Z:
          type: number
          format: float
          description:  "rotational speed"
    Error:
      required: 
        - message 
      properties: 
        message:
          type: string