all: test

test:
	# java -jar ~/Applications/openapi-generator-cli.jar generate -i api.yaml -g python-flask -o ../backend && \
	# java -jar ~/Applications/openapi-generator-cli.jar generate -i api.yaml -g cpp-qt-qhttpengine-server -o ../backend-cpp
	java -jar ~/Applications/openapi-generator-cli.jar generate -i test_api.yaml -g javascript -o ../html/js
